### ISSUE TITLE
Find a lightweight OS for dashboard

### ISSUE THREAD

**Issue by faraz-b** [sfuphantom/phantom-dashboard#6]
We need to ensure that the dashboard is not consuming a lot of system resources or power. Find the best lightweight OS to host the kivy dashboard app and to log data to a local server.

**Comment by courtenayhuffman** [comment]
Decided to use a server OS in order to minimize bloat and power consumption for better performance. Will install GUI if necessary. Will choose most lightweight option that can handle project requirements.

Requirements of OS:
MUST run python 3.7
MUST run kivy
SHOULD have ability to be hosted in a VM for development
SHOULD have option for GUI, or Desktop version of OS should exist
MUST be highly compatible with Raspberry Pi 4

**Comment by courtenayhuffman** [comment]
Researched Raspbian, Raspian Stretch Lite, Ubuntu Server, Lubuntu, Xubuntu, Gentoo, DietPi, CentOS, SUSE Linux Enterprise Server, Ubuntu Mate and Ubuntu Core as possible OS. 

Ubuntu Server seems like best option to try because:
1. Large community available for support 
2. Known compatibility with Python 3.7, kivy, Raspberry Pi 4
3. Ability to easily add GUI if desired
4. Lightweight to run
5. Can be run in VM for compatibility with dashboard GUI development, but existing environments should be compatible too

If this fails to work when tested, DietPi also would satisfy project requirements. It is likely more lightweight than Ubuntu server and comes with a GUI but has a smaller support community available, a higher learning curve for the team and is likely not fully compatible with existing environments for the dashboard GUI - this is why I think it shouldn't be the first option.

**Comment by faraz-b** [comment]
Ubuntu Server looks like a great choice right off the bat, especially because of the low system requirements. As long as we are able to add the required GUI libraries to display an application on the device then we are golden.

>     5. Can be run in VM for compatibility with dashboard GUI development, but existing environments should be compatible too

This is a really good point and important not to overlook as we could potentially develop everything and find out it doesn't actually run on the real thing. 

**Next Steps:**
- [ ] install Ubuntu Server and document steps to install OS
- [ ] install required libraries and packages to display the kivy dashboard app.
- [ ] clone the phantom-dashboard repo and successfully run the app

**Comment by courtenayhuffman** [comment]
dashboard needs a particular setup - with a /bin file and setup.py or requirements.txt in order to package dashboard to run on Ubuntu Core

**Comment by courtenayhuffman** [comment]
Kivy can't be packaged in Linux due to how Cython dependency is handled. Need OS that can run unpackaged programs (most, but not Ubuntu Core); and need way to run dashboard program upon booting up the Pi

**Comment by courtenayhuffman** [comment]
Raspberry Pi Lite will be used. Lightweight and compatible with existing stack
